---
- hosts: localhost
  connection: local

  vars:
    libs_ansible_version: "1.9.2-1"
    libs_jinja2_version: "2.7.3"
    libs_markupsafe_version: "0.23"
    libs_pyyaml_version: "3.11"

  tasks:
  - name: Create if not exists tmp/ directories structure
    file: path=../tmp/ state=directory mode=755
  
  - file: path=../tmp/archive/ state=directory mode=755
  - file: path=../tmp/ansible/ state=directory mode=755
  - file: path=../tmp/ansible/bin/ state=directory mode=755
  - file: path=../tmp/ansible/lib/ state=directory mode=755
  - file: path=../tmp/ansible/lib/__init__.py state=touch

  # ==========================================================
  # 
  # Ansible Core
  # 
  # ----------------------------------------------------------

  - name: "Ansible Core"
    get_url: 
      url: https://github.com/ansible/ansible/archive/v{{libs_ansible_version}}.tar.gz 
      dest: ../tmp/archive/ansible-v{{libs_ansible_version}}.tar.gz

  - unarchive: 
      src: ../tmp/archive/ansible-v{{libs_ansible_version}}.tar.gz
      dest: ../tmp/

  - command: cp -r ../tmp/ansible-{{libs_ansible_version}}/bin/ ../tmp/ansible/
  - command: cp -r ../tmp/ansible-{{libs_ansible_version}}/lib/ansible/ ../tmp/ansible/lib/

  - copy: src=../tmp/ansible-{{libs_ansible_version}}/plugins/callbacks/ dest=../tmp/ansible/lib/ansible/callback_plugins/
  - copy: src=../tmp/ansible-{{libs_ansible_version}}/plugins/inventory/ dest=../tmp/ansible/lib/ansible/inventory/

  # - name: "Ansible Core: chmod +x ansible/lib/ansible/inventory/*.py"
  #   command: find ../tmp/ansible/lib/ansible/inventory/ -name *.py -type f -exec chmod +x {} \;

  # ==========================================================
  # 
  # Ansible Modules (Core)
  # 
  # ----------------------------------------------------------

  - name: Ansible Modules (Core)
    get_url: 
      url: https://github.com/ansible/ansible-modules-core/archive/devel.tar.gz 
      dest: ../tmp/archive/ansible-modules-core-devel.tar.gz

  - unarchive: 
      src: ../tmp/archive/ansible-modules-core-devel.tar.gz
      dest: ../tmp/

  - command: cp -r ../tmp/ansible-modules-core-devel/ ../tmp/ansible/lib/ansible/modules/
  - file: path=../tmp/ansible/lib/ansible/modules/core state=absent
  - command: mv ../tmp/ansible/lib/ansible/modules/ansible-modules-core-devel ../tmp/ansible/lib/ansible/modules/core

  # ==========================================================
  # 
  # Ansible Modules (Extra)
  # 
  # ----------------------------------------------------------

  - name: "Ansible Modules (Extra)"
    get_url: 
      url: https://github.com/ansible/ansible-modules-extras/archive/devel.tar.gz 
      dest: ../tmp/archive/ansible-modules-extras-devel.tar.gz

  - unarchive: 
      src: ../tmp/archive/ansible-modules-extras-devel.tar.gz
      dest: ../tmp/

  - command: cp -r ../tmp/ansible-modules-extras-devel/ ../tmp/ansible/lib/ansible/modules/
  - file: path=../tmp/ansible/lib/ansible/modules/extras state=absent
  - command: mv ../tmp/ansible/lib/ansible/modules/ansible-modules-extras-devel ../tmp/ansible/lib/ansible/modules/extras

  # ==========================================================
  # 
  # Jinja2
  # 
  # ----------------------------------------------------------

  - name: "Jinja2"
    get_url: 
      url: https://github.com/mitsuhiko/jinja2/archive/{{libs_jinja2_version}}.tar.gz 
      dest: ../tmp/archive/jinja2-{{libs_jinja2_version}}.tar.gz

  - unarchive: 
      src: ../tmp/archive/jinja2-{{libs_jinja2_version}}.tar.gz
      dest: ../tmp/

  - command: cp -r ../tmp/jinja2-{{libs_jinja2_version}}/jinja2/ ../tmp/ansible/lib/

  # ==========================================================
  # 
  # MarkupSafe
  # 
  # ----------------------------------------------------------

  - name: "MarkupSafe"
    get_url: 
      url: https://github.com/mitsuhiko/markupsafe/archive/{{libs_markupsafe_version}}.tar.gz 
      dest: ../tmp/archive/markupsafe-{{libs_markupsafe_version}}.tar.gz

  - unarchive: 
      src: ../tmp/archive/markupsafe-{{libs_markupsafe_version}}.tar.gz
      dest: ../tmp/

  - command: cp -r ../tmp/markupsafe-{{libs_markupsafe_version}}/markupsafe/ ../tmp/ansible/lib/

  # ==========================================================
  # 
  # PyYAML
  # 
  # ----------------------------------------------------------

  - name: "PyYAML"
    get_url: 
      url: https://pypi.python.org/packages/source/P/PyYAML/PyYAML-{{libs_pyyaml_version}}.tar.gz
      dest: ../tmp/archive/pyyaml-{{libs_pyyaml_version}}.tar.gz

  - unarchive: 
      src: ../tmp/archive/pyyaml-{{libs_pyyaml_version}}.tar.gz
      dest: ../tmp/

  - command: cp -r ../tmp/PyYAML-{{libs_pyyaml_version}}/lib/yaml/ ../tmp/ansible/lib/

  # ==========================================================
  # 
  # Update package
  # 
  # ----------------------------------------------------------

  - name: Update Ansible package
    file: path=../ansible state=absent 
  - command: mv ../tmp/ansible ../ 

  # ==========================================================
  # 
  # Cleaning old files
  # 
  # ----------------------------------------------------------

  - name: Delete tmp/ directory if not exists tmp/ directory
    file: path=../tmp/ state=absent
